# Generated by Django 4.1.7 on 2023-03-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("passw", models.BinaryField(editable=True, max_length=1024)),
            ],
        ),
    ]
