# Generated by Django 4.1.7 on 2023-03-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_module", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="passw",
        ),
        migrations.AddField(
            model_name="user",
            name="_password",
            field=models.BinaryField(default=None, editable=True, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="_salt",
            field=models.BinaryField(default=b"", editable=True, max_length=4),
            preserve_default=False,
        ),
    ]
