# Generated by Django 4.1.7 on 2023-03-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_module", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="Booking",
        ),
    ]
